Organize a bit better

diff --git a/imagesizecheck b/imagesizecheck
--- a/imagesizecheck
+++ b/imagesizecheck
@@ -23,6 +23,13 @@ row_output=""
 nl=$'\n'
 sort_mode=true
 
+headings=(
+    "Bytes / Pixel"
+    "Dimensions"
+    "Image Size"
+    "Image Path"
+)
+
 function requirePackage() {
     if ! command -v "$1" > /dev/null; then
         if [[ "$1" == "identify" ]]; then
@@ -42,8 +49,6 @@ function requirePackage() {
     fi
 }
 
-requirePackage "identify"
-
 function findFiles() {
     local toolname="fd"
     if command -v fdfind > /dev/null; then
@@ -57,50 +62,6 @@ function findFiles() {
         eval "find $2"
     fi
 }
-
-if [[ "${*-""}" == "--version" ]]; then
-    echo "$(basename "$0") v$version"
-    exit
-elif [[ "${*-""}" == "--help" ]]; then
-    echo "Recursively lists images over a specified size in kilobytes (defaults to 75 KB). Displays pixel density (bytes per pixel), image dimensions, filesize, and image path."
-    echo
-    echo "Usage:   $(basename "$0") [size in kilobytes] [--nosort]"
-    echo "Example: $(basename "$0") 100 --nosort"
-    echo "Example: $(basename "$0") --version"
-    exit
-else
-    min_filesize="${1-75}"
-    sort_flag="${2-""}"
-
-    re='^[0-9]+$'
-    if ! [[ $min_filesize =~ $re ]] ; then
-        echo "Error: passed filesize must be a number! See \`$(basename "$0") -help\` for usage."
-        exit 1
-    fi
-
-    if [[ -n "$sort_flag" ]]; then
-        if [[ "$sort_flag" == "--nosort" ]]; then
-            sort_mode=false
-        else
-            echo "Invalid argument: $1. See \`$(basename "$0") -help\` for usage."
-            exit 1
-        fi
-    fi
-
-    result="$(
-        findFiles \
-            '--type f -e jpg -e png -e jpeg' \
-            '. -type f -not \( -path "*/vendor/*" \) -not \( -path "*/node_modules/*" \) -not \( -path "*/.git/*" \) \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \)' \
-            | sort
-    )"
-
-    if [[ -z "$result" ]]; then
-        echo "No images found."
-        exit 1
-    fi
-
-    total_total_count="$(echo "$result" | wc -l | xargs)"
-fi
 
 function getBytesPerPixel() {
     width="$1"
@@ -174,13 +135,6 @@ function percentageOfTotal() {
     echo "~$(bc <<< "scale=2; ($1 / $2) * 100")%"
 }
 
-headings=(
-    "Bytes / Pixel"
-    "Dimensions"
-    "Image Size"
-    "Image Path"
-)
-
 function outputHeadings() {
     pos=$(( ${#headings[*]} - 1 ))
     last=${headings[$pos]}
@@ -239,7 +193,55 @@ function removeTrailingNewline() {
     echo "$1" | awk 'NR>1{print PREV} {PREV=$0} END{printf("%s",$0)}'
 }
 
-function go() {
+function init() {
+    requirePackage "identify"
+
+    if [[ "${*-""}" == "--version" ]]; then
+        echo "$(basename "$0") v$version"
+        exit
+    elif [[ "${*-""}" == "--help" ]]; then
+        echo "Recursively lists images over a specified size in kilobytes (defaults to 75 KB). Displays pixel density (bytes per pixel), image dimensions, filesize, and image path."
+        echo
+        echo "Usage:   $(basename "$0") [size in kilobytes] [--nosort]"
+        echo "Example: $(basename "$0") 100 --nosort"
+        echo "Example: $(basename "$0") --version"
+        exit
+    else
+        min_filesize="${1:-"75"}"
+        sort_flag="${2:-""}"
+
+        re='^[0-9]+$'
+        if ! [[ $min_filesize =~ $re ]] ; then
+            echo "Error: passed filesize must be a number! See \`$(basename "$0") -help\` for usage."
+            exit 1
+        fi
+
+        if [[ -n "$sort_flag" ]]; then
+            if [[ "$sort_flag" == "--nosort" ]]; then
+                sort_mode=false
+            else
+                echo "Invalid argument: $1. See \`$(basename "$0") -help\` for usage."
+                exit 1
+            fi
+        fi
+
+        result="$(
+            findFiles \
+                '--type f -e jpg -e png -e jpeg' \
+                '. -type f -not \( -path "*/vendor/*" \) -not \( -path "*/node_modules/*" \) -not \( -path "*/.git/*" \) \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \)' \
+                | sort
+        )"
+
+        if [[ -z "$result" ]]; then
+            echo "No images found."
+            exit 1
+        fi
+
+        total_total_count="$(echo "$result" | wc -l | xargs)"
+    fi
+}
+
+function analyzeImages() {
     outputHeadings
 
     while read -r file; do
@@ -308,4 +310,5 @@ function go() {
     fi
 }
 
-go "${@-""}"
+init "${@:-""}"
+analyzeImages "${@:-""}"
